# Site
name: "PyElectrica"
title: "PyElectrica"
description: "Página web creada para el módulo de Python PyElectrica. En esta
página tambien se subiran artículos de uso del módulo y de la aplicación del
lenguaje de programación Python."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'pyelectrica'
mailchimp-list: 'https://pyelectrica.us8.list-manage.com/subscribe/post?u=33f298460d5da361abfec6484&amp;id=c0557e7d2d'
include: ["_pages"]
permalink: /:title/
email: isaix25@gmail.com

# Authors
authors:
  isai:
    name: Isai
    display_name: Isai
    gravatar: b17feda5b54b84df5b4912f640deacaa
    email: isaix25@gmail.com 
    web: https://github.com/x1sa1
    twitter: https://twitter.com/0001sa1000
    description: "Autor del módulo PyElectrica y de la página pyelectrica.ml, ingeniero eléctrico de profesión, con especialidad en Control e Iluminación, apasionado de la tecnología y de la programación."
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
